name: Build Docker Image and Generate SBOM

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-sbom:
    runs-on: ubuntu-latest

    steps:
      # 1. Reposunu çek
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Docker için Buildx ortamını kur
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Docker image'ı sadece build et (push yapmadan)
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false         # Buraya dikkat, push=false oldu
          load: true          # Docker engine içine image yüklensin
          tags: juice-shop:latest

      # 4. Syft'ı kur
      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

      # 5. SBOM dosyasını oluştur
      - name: Generate SBOM with Syft
        run: |
          syft juice-shop:latest -o spdx-json > sbom.spdx.json

      # 6. SBOM dosyasını artefakt olarak kaydet
      - name: Upload SBOM as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: juice-shop-sbom
          path: sbom.spdx.json
