name: Build Docker Image, Generate SBOM, Run Semgrep and Gitleaks

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-sbom:
    runs-on: ubuntu-latest

    steps:
      # 1. Reposunu çek
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Docker için Buildx ortamını kur
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Docker image'ı sadece build et (push yapmadan)
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          load: true
          tags: juice-shop:latest

      # 4. Syft'ı kur
      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | bash -s -- -b /usr/local/bin

      # 5. SBOM dosyasını oluştur
      - name: Generate SBOM with Syft
        run: |
          syft juice-shop:latest -o spdx-json > sbom.spdx.json

      # 6. SBOM dosyasını artefakt olarak kaydet
      - name: Upload SBOM as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: juice-shop-sbom
          path: sbom.spdx.json

  semgrep-scan:
    runs-on: ubuntu-latest
    continue-on-error: true  # Bu satırı ekledik, hata alırsa workflow devam eder.

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Bash kullanarak kurulum yapıyoruz
      - name: Install Semgrep
        run: |
          curl -sSfL https://github.com/returntocorp/semgrep/releases/latest/download/semgrep-linux-amd64 -o /usr/local/bin/semgrep
          chmod +x /usr/local/bin/semgrep

      # SARIF çıktısı ve strict mode ile Semgrep taraması
      - name: Run Semgrep scan and output SARIF (strict)
        run: |
          semgrep --config=auto --sarif --strict --output=semgrep-results.sarif

      - name: Upload Semgrep SARIF Results as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-sarif-results
          path: semgrep-results.sarif

  gitleaks-scan:
    runs-on: ubuntu-latest
    continue-on-error: true  # Bu satırı ekledik, hata alırsa workflow devam eder.

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Gitleaks Action'ı doğrudan kullanıyoruz
      - name: Run Gitleaks scan and output SARIF
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --source . --report-format sarif --report-path gitleaks-results.sarif

      - name: Upload Gitleaks SARIF Results as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-sarif-results
          path: gitleaks-results.sarif
